config/routes.rb
Rails.application.routes.draw do
  resources :private_invites

  root 'events#index'

  devise_for :users
  resources :users do
    resources :events
    resources :attendees
    resources :private_invites
  end

  resources :events do
    member do
      get 'cancel_rsvp'
    end
    resources :attendees
    resources :private_invites
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :user, foreign_key: "user_id", class_name: "User"
  belongs_to :event, foreign_key: "event_id", class_name: "Event"
  validates :user_id, uniqueness: { scope: :event_id }
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :owner, foreign_key: 'owner_id', class_name: "User"

    has_many :attendees, foreign_key: 'event_id', dependent: :destroy
    has_many :user_attendees, through: :attendees, source: :user

    has_many :private_invites, foreign_key: 'event_id', dependent: :destroy
    has_many :invited_users, through: :private_invites, source: :user
end

app/models/private_invite.rb
class PrivateInvite < ApplicationRecord
  belongs_to :event, foreign_key: 'event_id'
  belongs_to :user, foreign_key: 'user_id'
  validates :user_id, uniqueness: { scope: :event_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :events, foreign_key: 'owner_id', dependent: :destroy

  has_many :attendees
  has_many :attended_events, through: :attendees, source: :event

  has_many :private_invites, dependent: :destroy
  has_many :invited_events, through: :private_invites, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_attendee, only: %i[ show edit update destroy ]

  # GET /attendees or /attendees.json
  def index
    @attendees = Attendee.all
  end

  # GET /attendees/1 or /attendees/1.json
  def show
  end

  # GET /attendees/new
  def new
    @event = Event.find(params[:event_id])
    @attendee = @event.attendees.new
  end

  # GET /attendees/1/edit
  def edit
  end


  # POST /attendees or /attendees.json
  def create
    @event = Event.find(params[:event_id])
    @attendee = @event.attendees.build(attendee_params)
    @attendee.user_id = current_user.id
    respond_to do |format|
      if @attendee.save
        format.html { redirect_to event_path(@event), notice: "Attendee was successfully created." }
        format.json { render :show, status: :created, location: @attendee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendees/1 or /attendees/1.json
  def update
    respond_to do |format|
      if @attendee.update(attendee_params)
        format.html { redirect_to attendee_url(@attendee), notice: "Attendee was successfully updated." }
        format.json { render :show, status: :ok, location: @attendee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendees/1 or /attendees/1.json
  def destroy
    @attendee = Attendee.find(params[:user_id])
    @attendee.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Attendee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendee
      @attendee = Attendee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attendee_params
      params.require(:attendee).permit(:name, :event_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index
        @events = Event.where(private: false)
        @private_events = current_user.invited_events if current_user
    end

    def show
        @event = Event.find(params[:id])
        @attendees = @event.attendees
        @attendee = current_attendee?(@event)
    end

    def new
        @event = current_user.events.new
    end

    def create
        @event = current_user.events.build(event_params)
        if @event.save
            redirect_to root_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    def cancel_rsvp
        @attendee = Attendee.find(params[:id])
        @event = Event.find(@attendee.event_id)
        @attendee.destroy
        redirect_to event_path(@event)
    end

    private
        def event_params
            params.require(:event).permit(:title, :location, :description, :date, :private)
        end

        def current_attendee?(event)
            if event.user_attendees.exists?(current_user.id)
                event.attendees.find_by(user_id: current_user.id)
            else
                nil
            end
        end

end

app/controllers/private_invites_controller.rb
class PrivateInvitesController < ApplicationController
  before_action :set_private_invite, only: %i[ show edit update destroy ]

  # GET /private_invites or /private_invites.json
  def index
    @private_invites = PrivateInvite.all
  end

  # GET /private_invites/1 or /private_invites/1.json
  def show
  end

  # GET /private_invites/new
  def new
    @event = Event.find(params[:event_id])
    @private_invite = @event.private_invites.build
  end

  # GET /private_invites/1/edit
  def edit
  end

  # POST /private_invites or /private_invites.json
  def create
    @event = Event.find(params[:event_id])
    @private_invite = @event.private_invites.build(private_invite_params)
    @user = User.find_by(email: @private_invite.email)
    @private_invite.user_id = @user.id

    respond_to do |format|
      if @private_invite.save!
        format.html { redirect_to private_invite_url(@private_invite), notice: "Private invite was successfully created." }
        format.json { render :show, status: :created, location: @private_invite }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @private_invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /private_invites/1 or /private_invites/1.json
  def update
    respond_to do |format|
      if @private_invite.update(private_invite_params)
        format.html { redirect_to private_invite_url(@private_invite), notice: "Private invite was successfully updated." }
        format.json { render :show, status: :ok, location: @private_invite }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @private_invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /private_invites/1 or /private_invites/1.json
  def destroy
    @private_invite.destroy

    respond_to do |format|
      format.html { redirect_to private_invites_url, notice: "Private invite was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_private_invite
      @private_invite = PrivateInvite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def private_invite_params
      params.require(:private_invite).permit(:event_id, :user_id, :email)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.search(params[:search])
    end

    def show
        @user = User.find(params[:id])
    end

    def self.search(search)
        if search
            invitee = User.find_by(email: search)
            if invitee
                invitee
            end
        end
        nil
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/private_invites_helper.rb
module PrivateInvitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendees/_attendee.html.erb
<div id="<%= dom_id attendee %>">
  <p>
    <strong>User:</strong>
    <%= attendee.user_id %>
  </p>

  <p>
    <strong>Event:</strong>
    <%= attendee.event_id %>
  </p>

</div>

app/views/attendees/_form.html.erb
<%= form_with model: [@event, @event.attendees.build] do |form| %>
  <% if attendee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(attendee.errors.count, "error") %> prohibited this attendee from being saved:</h2>

      <ul>
        <% attendee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
    <%= form.hidden_field :event_id, value: @event.id%>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/attendees/edit.html.erb
<h1>Editing attendee</h1>

<%= render "form", attendee: @attendee %>

<br>

<div>
  <%= link_to "Show this attendee", @attendee %> |
  <%= link_to "Back to attendees", attendees_path %>
</div>

app/views/attendees/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Attendees</h1>

<div id="attendees">
  <% @attendees.each do |attendee| %>
    <%= render attendee %>
    <p>
      <%= link_to "Show this attendee", attendee %>
    </p>
  <% end %>
</div>

<%= link_to "New attendee", new_attendee_path %>

app/views/attendees/new.html.erb
<h1>New attendee</h1>

<%= render "form", attendee: @attendee %>

<br>

<div>
  <%= link_to "Back to attendees", event_attendees_path %>
</div>

app/views/attendees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @attendee %>

<div>
  <%= link_to "Edit this attendee", edit_attendee_path(@attendee) %> |
  <%= link_to "Back to attendees", attendees_path %>

  <%= button_to "Destroy this attendee", @attendee, method: :delete %>
</div>

app/views/events/_form.html.erb
<%= form_with model: [current_user, current_user.events.build] do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :location %>
        <%= form.text_field :location %>
    </div>
    <div>
        <%= form.label :description %>
        <%= form.text_area :description %>
    </div>
    <div>
        <%= form.label :date %>
        <%= form.datetime_field :date %>
    </div>
    <div>
        <%= form.label :private %>
        <%= form.check_box :private %>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/events/index.html.erb
<h1>Events</h1>


<ul>
    <div><h3>Public Events:</h3></div>
    <% @events.each do |event| %>
        <li>
            <h1><%= link_to event.title, event_path(event) %></h1>
            <div><%= event.location %></div>
        </li>
    <% end %>
</ul>

<% if user_signed_in? && !@private_events.empty? %>
    <ul>
        <div><h3>Private Events:</h3></div>
        <% @private_events.each do |event| %>
            <li>
                <h1><%= link_to event.title, event_path(event) %></h1>
                <div><%= event.location %></div>
            </li>
        <% end %>
    </ul>
<% end %>

<div>
    <% if user_signed_in? %>
        <div>
            <div>
                <%= link_to "New Event", new_user_event_path(current_user) %>
            </div>
            <div>
                <%= link_to "Your events", user_path(current_user) %>
            </div>
        </div>

        <div> 
            <%= link_to "Log-out", destroy_user_session_path, data: { "turbo-method": :delete }%> Logged in as: <%= current_user.email %> 
        </div>
    <% else %>
        <div><%= link_to "Log-in", new_user_session_path %></div>
         <div><%= link_to "Create Account", new_user_registration_path %></div>
    <% end %>

</div>

app/views/events/new.html.erb
<h1>Create Event</h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<h1> <%= @event.title %> </h1>

<div>
    <div>
        <%= @event.location %>
    </div>
    <div>
        <%= @event.description %>
    </div>
    <div>
        <%= @event.date %>
    </div>
</div>

<div>
    <h4>Attendees</h4>
    <ul>
        <% @attendees.each do |p| %>
            <li><%= p.name %></li>
        <% end %>
    </ul>
</div>

<div>
    <% if user_signed_in? %>
        <% if @attendee %>
            <%= link_to "Leave Event", cancel_rsvp_event_path(@attendee)%>
        <% else %>
            <%= link_to "Attend Event", new_event_attendee_path(@event), method: :post %>
        <% end %>
    <% end %>
</div>
<div>
    <div>
        <%= link_to "All Events", root_url %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/private_invites/_form.html.erb
<%= form_with model: [@event, @event.private_invites.build] do |form| %>
  <% if private_invite.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(private_invite.errors.count, "error") %> prohibited this private_invite from being saved:</h2>

      <ul>
        <% private_invite.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= form.label :email, style: "display:block" %>
    <%= form.text_field :email %>
    <%= form.hidden_field :event_id, value: @event.id %>
    <%= form.submit %>
  </div>
<% end %>

app/views/private_invites/_private_invite.html.erb
<div id="<%= dom_id private_invite %>">
</div>

app/views/private_invites/edit.html.erb
<h1>Editing private invite</h1>

<%= render "form", private_invite: @private_invite %>

<br>

<div>
  <%= link_to "Show this private invite", @private_invite %> |
  <%= link_to "Back to private invites", private_invites_path %>
</div>

app/views/private_invites/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Private invites</h1>

<div id="private_invites">
  <% @private_invites.each do |private_invite| %>
    <%= render private_invite %>
    <p>
      <%= link_to "Show this private invite", private_invite %>
    </p>
  <% end %>
</div>

<%= link_to "New private invite", new_private_invite_path %>

app/views/private_invites/new.html.erb
<h1>New private invite</h1>

<%= render "form", private_invite: @private_invite %>

<br>

<div>
  <%= link_to "Back to private invites", private_invites_path %>
</div>

app/views/private_invites/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @private_invite %>

<div>
  <%= link_to "Edit this private invite", edit_private_invite_path(@private_invite) %> |
  <%= link_to "Back to private invites", private_invites_path %>

  <%= button_to "Destroy this private invite", @private_invite, method: :delete %>
</div>

app/views/users/show.html.erb
<h1><%=current_user.email%>'s Events</h1>

<div>
    <% @user.events.each do |event| %>
        <div>
            <h1><%= event.title %></h1>
            <div><%= event.location %></div>
            <div><%= event.description %>
            <div><%= event.date %>
            <div><%= link_to "Invite User", new_event_private_invite_path(event)%>
        </div>
    <% end %>
</div>
<div>
    <ul>
        <h2>Upcoming Events</h2>
        <% @user.attended_events.where('date >= ?', Date.today).each do |event| %>
            <li><%= event.title %></li>
            <div>
                <%= link_to "Leave Event", user_event_path(event), method: :show %> 
            </div>
        <% end %>
    </ul>

    <ul>
        <h2>Past Events</h2>
        <% @user.attended_events.where('date < ?', Date.today).each do |event| %>
            <li><%= event.title %></li>
        <% end %>
    </ul>
</div>
<div>
    <div>
        <%= link_to "New Event", new_user_event_path(current_user) %>
    </div>
    <div>
        <%= link_to "All Events", root_url %>
    </div>
</div>